### ISSUE TITLE
train labels different from training folder

### ISSUE THREAD

**Issue by zook111** [radekosmulski/rsna-intracranial#1]
Hi
Thanks for a fantastic introduction.
Am having issues with creating databunch from 3rd notebook.
My 112/train images all start with ID_81........png  , but this does not match labels in train_labels_as_strings.csv
Am I missing a step somewhere??
Thanks

**Comment by radekosmulski** [comment]
Hi! This is how the file looks for me:

![image](https://user-images.githubusercontent.com/2444926/66422090-5600a980-ea09-11e9-9615-b492776e47f4.png)

It gets created in `02_reshape_train_csv.ipynb`. Could you please rerun the unmodified notebook? I think this should fix the issue for you. Let me know how it goes

**Comment by zook111** [comment]
Hmm, not sure whats going on here. I still get error message below , and data.showbatch() on following line gives FileNotFoundError: [Errno 2] No such file or directory: 'data/112/train/ID_fb9888de5.png'

/home/zook/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/basic_data.py:259: UserWarning: There seems to be something wrong with your dataset, for example, in the first batch can't access these elements in self.train_ds: 378598,445813,28701,495221,53499...
  warn(warn_msg)

![Screenshot from 2019-10-09 01-46-38](https://user-images.githubusercontent.com/451970/66443520-56179e00-ea37-11e9-8df3-7811441ff316.png)
![Screenshot from 2019-10-09 01-47-19](https://user-images.githubusercontent.com/451970/66443521-56b03480-ea37-11e9-9ba7-324ee875a6c7.png)
![Screenshot from 2019-10-09 01-47-47](https://user-images.githubusercontent.com/451970/66443522-56b03480-ea37-11e9-8093-b2533a7cf9e2.png)
![Screenshot from 2019-10-09 01-48-33](https://user-images.githubusercontent.com/451970/66443523-56b03480-ea37-11e9-8294-1a526971d31a.png)

**Comment by radekosmulski** [comment]
Sorry, only now saw your comment. Getting too many msgs from Github, will need to look at filtering some of them automatically.

Seems like you don't have the files in  `data/112/train/`. Did you run NB 01 and did it complete successfully? 

You can check how many files you have in `data/112/train` using this command from terminal on Linux: `ls data/112/train/ | wc -l`. If I ran this command from the root of the repository it finds 674257 files.

Sorry for the late response again - will figure out the notification situation with emails from github.

**Comment by zook111** [comment]
No worries, appreciate the help. Command show 350477 files in 112/train.
Strange, will try downloading again.
